<?php

$title = 'Edit task';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$title = $form->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Task title');

$description = $form->get('description');
$description->setAttribute('class', 'form-control');
$description->setAttribute('placeholder', 'Description');

$status = $form->get('status');
$status->setAttribute('class', 'form-control');
$status->setAttribute('placeholder', 'Status');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('task', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($title) ?>
    <?= $this->formElement($title) ?>
    <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($description) ?>
    <?= $this->formElement($description) ?>
    <?= $this->formElementErrors()->render($description, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($status) ?>
    <?= $this->formElement($status) ?>
    <?= $this->formElementErrors()->render($status, ['class' => 'help-block']) ?>
</div>
<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();